language: ruby

rvm:
  - 2.4.2
  - 2.5.0
  - 2.6.5
  - ruby-head

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.1-stable
  - gemfiles/Gemfile.rails-4.2-stable
  - gemfiles/Gemfile.rails-5.0-stable
  - gemfiles/Gemfile.rails-5.1-stable

matrix:
  exclude:
    - rvm: 2.4.2
      gemfile: Gemfile
    - rvm: 2.4.2
      gemfile: gemfiles/Gemfile.rails-4.1-stable
    - rvm: 2.5.0
      gemfile: gemfiles/Gemfile.rails-4.1-stable
    - rvm: 2.6.5
      gemfile: gemfiles/Gemfile.rails-4.1-stable
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-4.1-stable
  allow_failures:
    - rvm: ruby-head

sudo: false

before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - gem update --system

before_script: 'bundle update'