HelloWorldDbMailer:
  subject: '{{app_name}} - Hello world!'
  from: Site <no-reply@example.com>
  to: '{{user_name}} <{{user_email}}>'
  body: >
    Hello, {{user_name}}!<br><br>
    This is your first e-mail with <b>DbMailerRails gem</b> :)<br><br>
    Don't forget to "Star" this <a href="https://github.com/thoughtbot/paperclip">gem on GitHub</a>.